language: cpp
compiler:
- g++
os:
- linux
- osx
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
- if [ "$CXX" == "clang++" ]; then export CXXFLAGS="-stdlib=libc++"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
script: make test